### ISSUE TITLE
Bug in AzureStor::list_adls_files()

### ISSUE THREAD

**Issue by taekeharkema** [Azure/AzureStor#39] opened 2020-01-31 10:42 UTC
Hi,

There appears to be a bug in `AzureStor::list_adls_files()` when more than 5k files exist in the filesystem. An -almost- reprex (I presumably shouldn't share our key :) ):

```
library(AzureStor)

endpoint_url <- "<endpoint>.dfs.core.windows.net"
filesystem_name <- "<filesystem_name>"
key = "<access_key>"

endpoint <- AzureStor::storage_endpoint(endpoint = endpoint_url, key = key)
filesystem <- AzureStor::adls_filesystem(endpoint, name = filesystem_name)

AzureStor::list_adls_files(filesystem, recursive = TRUE)
```
gives an error:

```
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```
In our case, the `repeat`-block in `list_adls_files` generates an eight-column dataframe in the first loop, with names:
```
> names(out)
[1] "contentLength" "etag"          "group"         "isDirectory"   "lastModified"  "name"          "owner"        
[8] "permissions"
```
In the second loop, the content of out has only seven columns, missing the "isDirectory" column:
```
> names(out2)
[1] "contentLength" "etag"          "group"         "lastModified"  "name"          "owner"         "permissions"  
```

**Comment by Hong-Revo** [comment] 2020-01-31 12:03
Hi, thanks for the report. Just some questions:

- Does this account have hierarchical namespaces enabled?
- Was the filesystem originally created as a blob container?

It's possible there may still be some glitches in the ADLS/blob interop system.

**Comment by taekeharkema** [comment] 2020-01-31 16:52
Hi,

Thanks for your quick reply!

* Yes, it is a gen2 ADLS with hierarchical namespaces enabled.
* I'm not sure I fully understand your question, but am inclined to anser "no", it being a Gen2-ADLS and a filesystem created (I _think_) with `AzureStor::create_adls_filesystem()`, but I'm not sure. Is there a way to check? To be honest, the ADLS-nomenclature does somewhat confuse me sometimes..

**Comment by Hong-Revo** [comment] 2020-01-31 19:46
ADLSgen2 and blob storage are interoperable as of the start of this year, meaning that you can access both types of storage with either API. Eg you can create a blob container and then upload/download files with ADLS2, or create an ADLS2 filesystem and upload/download with blob. There was a lot of work by the broader Storage team to make the two APIs play nice with each other, and there may be a few bugs lurking still.

I can't reproduce the bug with a new ADLS2 filesystem, on an account with HNS enabled. Can you verify how your container was created?

- Was it via the portal, or Storage Explorer, or using AzureStor
- Was it created as a blob container or ADLS filesystem

**Comment by Hong-Revo** [comment] 2020-02-18 14:30
@taekeharkema is this still an issue? If so, are you able to provide any info on how the account and container were originally created?

**Comment by Sentewolf** [comment] 2020-02-21 12:30
I was able to reproduce this issue in several ways.

Three ways to create the storage account:
1. create a storage with a template through PowerShell with HNS enabled
2. create a storage manually in the Azure Portal with HNS enabled
3. create a storage manually in the Azure Portal with HNS disabled

Five ways to create the filesystem/blob container:
a. create a filesystem with a template through PowerShell
b. create a filesystem in the Storage Explorer
c. create a filesystem using AzureStor::create_adls_filesystem()
d. create a blob container in the Storage Explorer
e. create a blob container using AzureStor::create_adls_filesystem()

I tested the following combinations: [1a, 1b, 2a, 2b, 2c, 3d, 3e]

After creating the filesystem/blob container, I created 10001 files on a VM in the same resource group:

```
mkdir data
cd data
dd if=/dev/zero of=masterfile bs=1 count=1000000
split -b 10 -a 10 masterfile
```

Using AzureStor, I copied at least 5000 files to the filesystem/blob container (terminating the process once the Storage Explorer showed at least 5000 files):
```
AzureStor::multiupload_adls_file(filesystem, "~/data/*", "data/", recursive=TRUE)
```

Finally, we try to list all files:
```
> AzureStor::list_adls_files(filesystem, recursive = TRUE)
Error in rbind(deparse.level, ...) :
  numbers of columns of arguments do not match
```

---

The template with which the storage account was created:

```
{
	"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
	},
	"variables": {},
	"resources": [
		{
			"type": "Microsoft.Storage/storageAccounts",
			"apiVersion": "2019-04-01",
			"name": "temporarytestadls",
			"location": "West Europe",
			"tags": {
			},
			"sku": {
				"name": "Standard_LRS",
				"tier": "Standard"
			},
			"kind": "StorageV2",
			"properties": {
				"isHnsEnabled": true,
				"networkAcls": {
					"bypass": "AzureServices",
					"virtualNetworkRules": [],
					"ipRules": [],
					"defaultAction": "Allow"
				},
				"supportsHttpsTrafficOnly": true,
				"encryption": {
					"services": {
						"file": {
							"enabled": true
						},
						"blob": {
							"enabled": true
						}
					},
					"keySource": "Microsoft.Storage"
				},
				"accessTier": "Hot"
			}
		},
        {
            "type": "Microsoft.Storage/storageAccounts/blobServices",
            "apiVersion": "2019-04-01",
            "name": "temporarytestadls/default",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts', 'temporarytestadls')]"
            ],
            "properties": {
                "cors": {
                    "corsRules": []
                },
                "deleteRetentionPolicy": {
                    "enabled": false
                }
            }
        },
		{
			"type": "Microsoft.Storage/storageAccounts/blobServices/containers",
			"apiVersion": "2019-04-01",
			"name": "temporarytestadls/default/projectdata",
			"dependsOn": [
				"[resourceId('Microsoft.Storage/storageAccounts/blobServices', 'temporarytestadls', 'default')]",
				"[resourceId('Microsoft.Storage/storageAccounts', 'temporarytestadls')]"
			],
			"properties": {
				"publicAccess": "None"
			}
		}
	]
}
```

in the Azure Portal, I opened a PowerShell terminal, uploaded the template as storage.json and entered the following commands:

```
Connect-AzAccount
$templatefile = "$HOME/storage.json"
New-AzResourceGroupDeployment -TemplateFile $templatefile -ResourceGroupName <resource_group_name>
```

**Comment by Sentewolf** [comment] 2020-02-21 13:01
I get varying results, depending on the exact call to AzureStor::list_adls_files.

Without a directory:
```
> res = AzureStor::list_adls_files(filesystem, recursive=TRUE)
Error in rbind(deparse.level, ...) :
  numbers of columns of arguments do not match
```

With a directory specified:
```
> res = AzureStor::list_adls_files(filesystem, "data", recursive=TRUE)
> nrow(res)
[1] 10226
```

**Comment by Hong-Revo** [comment] 2020-02-21 20:43
Thanks so much for that, @Sentewolf! Just so it's clear, which specific method(s) of creating the account/filesystem triggered the bug?

**Comment by Sentewolf** [comment] 2020-02-21 21:26
My apologies if that was unclear. All methods lead to the bug. I am unable
to _not_ reproduce the bug, except by changing the arguments to the
list_adls_files call as in my previous comment.

I agree the problem is in the return value from the Azure API if no
directories are present and you request a Path list from the root
directory, as @taekeharkema said. The isDirectory column is not returned if
only files are found (which happens in the second iteration for a folder
with more than 5000 files).

Perhaps we should call it a bug in the API (do you know where to submit
those?), but it might still be nice if AzureStor won't fail on it. The fix
could lie in extending the rbind call to take the combined set of columns
of the first and subsequent continuations (which is a bit ugly with base
R).

**Comment by Hong-Revo** [comment] 2020-02-22 07:42
I've pushed a fix in the adls-listfiles-fix branch. Let me know if that doesn't get things working.

**Comment by Sentewolf** [comment] 2020-02-24 08:13
Excellent, solves the problem for me!

**Closed** 2020-02-24 19:10 UTC
